In [ ]:
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go

import warnings
warnings.filterwarnings('ignore')

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
df = pd.read_csv(r'/content/drive/MyDrive/Colab Notebooks/World_Stock_Prices_Dataset.csv')
df

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits,Brand_Name,Ticker,Industry_Tag,Country,Capital Gains
0,2025-03-20 00:00:00-04:00,386.899994,397.820007,385.799988,389.609985,4003800,0.0,0.0,adobe,ADBE,technology,usa,NaN
1,2025-03-20 00:00:00-04:00,131.100006,132.289993,130.210007,130.509995,378500,0.0,0.0,lvmh,LVMUY,luxury goods,france,NaN
2,2025-03-20 00:00:00-04:00,236.559998,241.759995,236.199997,239.009995,8321600,0.0,0.0,jpmorgan chase & co,JPM,finance,usa,NaN
3,2025-03-20 00:00:00-04:00,60.480000,61.020000,60.340000,60.619999,16503100,0.0,0.0,cisco,CSCO,technology,usa,NaN
4,2025-03-20 00:00:00-04:00,59.020000,59.290001,58.689999,59.230000,2840400,0.0,0.0,unilever,UL,consumer goods,netherlands,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
305209,2000-01-03 00:00:00-05:00,13.822670,13.822670,13.675379,13.720699,48000,0.0,0.0,honda,HMC,automotive,japan,NaN
305210,2000-01-03 00:00:00-05:00,3.990652,4.061914,3.848129,3.990652,134500,0.0,0.0,nintendo,NTDOY,gaming,japan,NaN
305211,2000-01-03 00:00:00-05:00,31.512873,31.512873,30.431443,30.799129,6057400,0.0,0.0,costco,COST,retail,usa,NaN
305212,2000-01-03 00:00:00-05:00,38.147537,38.255972,35.935457,37.496925,53076000,0.0,0.0,cisco,CSCO,technology,usa,NaN
305213,2000-01-03 00:00:00-05:00,5.731675,5.793975,5.427959,5.482471,5825700,0.0,0.0,american eagle outfitters,AEO,apparel,usa,NaN

In [ ]:
df.head()

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits,Brand_Name,Ticker,Industry_Tag,Country,Capital Gains
0,2025-03-20 00:00:00-04:00,386.899994,397.820007,385.799988,389.609985,4003800,0.0,0.0,adobe,ADBE,technology,usa,NaN
1,2025-03-20 00:00:00-04:00,131.100006,132.289993,130.210007,130.509995,378500,0.0,0.0,lvmh,LVMUY,luxury goods,france,NaN
2,2025-03-20 00:00:00-04:00,236.559998,241.759995,236.199997,239.009995,8321600,0.0,0.0,jpmorgan chase & co,JPM,finance,usa,NaN
3,2025-03-20 00:00:00-04:00,60.480000,61.020000,60.340000,60.619999,16503100,0.0,0.0,cisco,CSCO,technology,usa,NaN
4,2025-03-20 00:00:00-04:00,59.020000,59.290001,58.689999,59.230000,2840400,0.0,0.0,unilever,UL,consumer goods,netherlands,NaN

In [ ]:
df.tail()

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits,Brand_Name,Ticker,Industry_Tag,Country,Capital Gains
305209,2000-01-03 00:00:00-05:00,13.822670,13.822670,13.675379,13.720699,48000,0.0,0.0,honda,HMC,automotive,japan,NaN
305210,2000-01-03 00:00:00-05:00,3.990652,4.061914,3.848129,3.990652,134500,0.0,0.0,nintendo,NTDOY,gaming,japan,NaN
305211,2000-01-03 00:00:00-05:00,31.512873,31.512873,30.431443,30.799129,6057400,0.0,0.0,costco,COST,retail,usa,NaN
305212,2000-01-03 00:00:00-05:00,38.147537,38.255972,35.935457,37.496925,53076000,0.0,0.0,cisco,CSCO,technology,usa,NaN
305213,2000-01-03 00:00:00-05:00,5.731675,5.793975,5.427959,5.482471,5825700,0.0,0.0,american eagle outfitters,AEO,apparel,usa,NaN

In [ ]:
df.size

3967782

In [ ]:
df.shape

(305214, 13)

In [ ]:
df.columns

Index(['Date', 'Open', 'High', 'Low', 'Close', 'Volume', 'Dividends',
       'Stock Splits', 'Brand_Name', 'Ticker', 'Industry_Tag', 'Country',
       'Capital Gains'],
      dtype='object')

In [ ]:
df.describe

<bound method NDFrame.describe of                              Date        Open        High         Low  \
0       2025-03-20 00:00:00-04:00  386.899994  397.820007  385.799988
1       2025-03-20 00:00:00-04:00  131.100006  132.289993  130.210007
2       2025-03-20 00:00:00-04:00  236.559998  241.759995  236.199997
3       2025-03-20 00:00:00-04:00   60.480000   61.020000   60.340000
4       2025-03-20 00:00:00-04:00   59.020000   59.290001   58.689999
...                           ...         ...         ...         ...
305209  2000-01-03 00:00:00-05:00   13.822670   13.822670   13.675379
305210  2000-01-03 00:00:00-05:00    3.990652    4.061914    3.848129
305211  2000-01-03 00:00:00-05:00   31.512873   31.512873   30.431443
305212  2000-01-03 00:00:00-05:00   38.147537   38.255972   35.935457
305213  2000-01-03 00:00:00-05:00    5.731675    5.793975    5.427959

             Close    Volume  Dividends  Stock Splits  \
0       389.609985   4003800        0.0           0.0
1       130.509995    378500        0.0           0.0
2       239.009995   8321600        0.0           0.0
3        60.619999  16503100        0.0           0.0
4        59.230000   2840400        0.0           0.0
...            ...       ...        ...           ...
305209   13.720699     48000        0.0           0.0
305210    3.990652    134500        0.0           0.0
305211   30.799129   6057400        0.0           0.0
305212   37.496925  53076000        0.0           0.0
305213    5.482471   5825700        0.0           0.0

                       Brand_Name Ticker    Industry_Tag      Country  \
0                           adobe   ADBE      technology          usa
1                            lvmh  LVMUY    luxury goods       france
2             jpmorgan chase & co    JPM         finance          usa
3                           cisco   CSCO      technology          usa
4                        unilever     UL  consumer goods  netherlands
...                           ...    ...             ...          ...
305209                      honda    HMC      automotive        japan
305210                   nintendo  NTDOY          gaming        japan
305211                     costco   COST          retail          usa
305212                      cisco   CSCO      technology          usa
305213  american eagle outfitters    AEO         apparel          usa

        Capital Gains
0                 NaN
1                 NaN
2                 NaN
3                 NaN
4                 NaN
...               ...
305209            NaN
305210            NaN
305211            NaN
305212            NaN
305213            NaN

[305214 rows x 13 columns]>

In [ ]:
df.dtypes

Date              object
Open             float64
High             float64
Low              float64
Close            float64
Volume             int64
Dividends        float64
Stock Splits     float64
Brand_Name        object
Ticker            object
Industry_Tag      object
Country           object
Capital Gains    float64
dtype: object

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 305214 entries, 0 to 305213
Data columns (total 13 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   Date           305214 non-null  object
 1   Open           305214 non-null  float64
 2   High           305214 non-null  float64
 3   Low            305214 non-null  float64
 4   Close          305214 non-null  float64
 5   Volume         305214 non-null  int64
 6   Dividends      305214 non-null  float64
 7   Stock Splits   305214 non-null  float64
 8   Brand_Name     305214 non-null  object
 9   Ticker         305214 non-null  object
 10  Industry_Tag   305214 non-null  object
 11  Country        305214 non-null  object
 12  Capital Gains  2 non-null       float64
dtypes: float64(7), int64(1), object(5)
memory usage: 30.3+ MB

#DATA CLEANING

In [ ]:
df=df.sort_values(by='Date').reset_index(drop=True)

In [ ]:
df.head()

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits,Brand_Name,Ticker,Industry_Tag,Country,Capital Gains
0,2000-01-03 00:00:00-05:00,5.731675,5.793975,5.427959,5.482471,5825700,0.0,0.0,american eagle outfitters,AEO,apparel,usa,NaN
1,2000-01-03 00:00:00-05:00,14.968750,15.593750,14.687500,15.500000,7843200,0.0,0.0,amd,AMD,technology,usa,NaN
2,2000-01-03 00:00:00-05:00,36.457976,36.846240,34.788441,36.205605,53228400,0.0,0.0,microsoft,MSFT,technology,usa,NaN
3,2000-01-03 00:00:00-05:00,23.135441,23.295548,22.495014,23.075401,2870400,0.0,0.0,target,TGT,retail,usa,NaN
4,2000-01-03 00:00:00-05:00,9.653981,9.765803,9.355788,9.467610,3277800,0.0,0.0,southwest airlines,LUV,aviation,usa,NaN

In [ ]:
df.tail()

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits,Brand_Name,Ticker,Industry_Tag,Country,Capital Gains
305209,2025-03-20 00:00:00-04:00,17.959999,17.959999,17.700001,17.770000,545600,0.0,0.0,nintendo,NTDOY,gaming,japan,NaN
305210,2025-03-20 00:00:00-04:00,106.820000,108.970001,105.379997,105.480003,1481100,0.0,0.0,crocs,CROX,footwear,usa,NaN
305211,2025-03-20 00:00:00-04:00,48.500000,49.349998,48.490002,49.000000,10706600,0.0,0.0,chipotle,CMG,food,usa,NaN
305212,2025-03-20 00:00:00-04:00,104.400002,106.669998,103.919998,104.199997,5853100,0.0,0.0,target,TGT,retail,usa,NaN
305213,2025-03-20 00:00:00-04:00,386.899994,397.820007,385.799988,389.609985,4003800,0.0,0.0,adobe,ADBE,technology,usa,NaN

In [ ]:
df['Date']=pd.to_datetime(df['Date'],utc=True).dt.date

#STANDARDIZING CATEGORY

In [ ]:
categorical_columns=df.select_dtypes(include=['object','category']).columns.tolist()
categorical_columns

['Date', 'Brand_Name', 'Ticker', 'Industry_Tag', 'Country']

In [ ]:
df['Brand_Name'].unique()

array(['american eagle outfitters', 'amd', 'microsoft', 'target',
       'southwest airlines', 'johnson & johnson', 'toyota', 'nike',
       'the coca-cola company', 'colgate palmolive', 'starbucks',
       'jpmorgan chase & co', 'logitech', 'the walt disney company',
       'philips', 'procter & gamble', 'nordstrom', 'cisco', '3m',
       'costco', 'nintendo', 'honda', 'foot locker', 'apple', 'nvidia',
       'the home depot', 'hershey company', 'fedex', 'american express',
       "mcdonald's", 'marriott', 'amazon', 'adobe', 'unilever', 'netflix',
       'salesforce / slack', 'google', 'chipotle', 'lvmh', 'crocs',
       'mastercard', 'adidas', 'delta air lines', 'visa', 'bmw group',
       'ubisoft', 'porsche', 'tesla', 'puma', 'hilton', 'shopify',
       'block', 'spotify', 'pinterest', 'zoom video communications',
       'uber', 'peloton', 'zoominfo', 'airbnb', 'roblox', 'coinbase'],
      dtype=object)

In [ ]:
df['Brand_Name'].nunique()

61

In [ ]:
df['Ticker'].unique()

array(['AEO', 'AMD', 'MSFT', 'TGT', 'LUV', 'JNJ', 'TM', 'NKE', 'KO', 'CL',
       'SBUX', 'JPM', 'LOGI', 'DIS', 'PHG', 'PG', 'JWN', 'CSCO', 'MMM',
       'COST', 'NTDOY', 'HMC', 'FL', 'AAPL', 'NVDA', 'HD', 'HSY', 'FDX',
       'AXP', 'MCD', 'MAR', 'AMZN', 'ADBE', 'UL', 'NFLX', 'CRM', 'GOOGL',
       'CMG', 'LVMUY', 'CROX', 'MA', 'ADDYY', 'DAL', 'V', 'BAMXF',
       'UBSFY', 'POAHY', 'TSLA', 'PMMAF', 'HLT', 'SHOP', 'SQ', 'SPOT',
       'PINS', 'ZM', 'UBER', 'PTON', 'ZI', 'ABNB', 'RBLX', 'COIN'],
      dtype=object)

In [ ]:
df['Ticker'].nunique()

61

In [ ]:
df['Industry_Tag'].unique()

array(['apparel', 'technology', 'retail', 'aviation', 'healthcare',
       'automotive', 'food & beverage', 'consumer goods', 'finance',
       'entertainment', 'manufacturing', 'gaming', 'footwear',
       'logistics', 'food', 'hospitality', 'e-commerce', 'luxury goods',
       'financial services', 'music', 'social media', 'fitness',
       'cryptocurrency'], dtype=object)

In [ ]:
df['Industry_Tag'].nunique()

23

In [ ]:
df['Country'].unique()

array(['usa', 'japan', 'switzerland', 'netherlands', 'france', 'germany',
       'canada'], dtype=object)

In [ ]:
df['Country'].nunique()

7

#HANDLING MISSING DATA

In [ ]:
df.isna().sum()

Date                  0
Open                  0
High                  0
Low                   0
Close                 0
Volume                0
Dividends             0
Stock Splits          0
Brand_Name            0
Ticker                0
Industry_Tag          0
Country               0
Capital Gains    305212
dtype: int64

#HANDLING DUPLICATE DATA

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df.drop('Capital Gains',inplace=True,axis=1)

In [ ]:
df.isna().sum()

Date            0
Open            0
High            0
Low             0
Close           0
Volume          0
Dividends       0
Stock Splits    0
Brand_Name      0
Ticker          0
Industry_Tag    0
Country         0
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
cat_cols=['Brand_Name', 'Ticker', 'Industry_Tag', 'Country']
for col in cat_cols:
  df[col]=df[col].astype('category')

In [ ]:
df['Date']=pd.to_datetime(df['Date'])
df['Date']

0        2000-01-03
1        2000-01-03
2        2000-01-03
3        2000-01-03
4        2000-01-03
            ...
305209   2025-03-20
305210   2025-03-20
305211   2025-03-20
305212   2025-03-20
305213   2025-03-20
Name: Date, Length: 305214, dtype: datetime64[ns]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 305214 entries, 0 to 305213
Data columns (total 12 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   Date          305214 non-null  datetime64[ns]
 1   Open          305214 non-null  float64
 2   High          305214 non-null  float64
 3   Low           305214 non-null  float64
 4   Close         305214 non-null  float64
 5   Volume        305214 non-null  int64
 6   Dividends     305214 non-null  float64
 7   Stock Splits  305214 non-null  float64
 8   Brand_Name    305214 non-null  category
 9   Ticker        305214 non-null  category
 10  Industry_Tag  305214 non-null  category
 11  Country       305214 non-null  category
dtypes: category(4), datetime64[ns](1), float64(6), int64(1)
memory usage: 19.8 MB

#FEATURED ENGINEERING

In [ ]:
df['Year']=df['Date'].dt.year

In [ ]:
df.head()

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits,Brand_Name,Ticker,Industry_Tag,Country,Year
0,2000-01-03,5.731675,5.793975,5.427959,5.482471,5825700,0.0,0.0,american eagle outfitters,AEO,apparel,usa,2000
1,2000-01-03,14.968750,15.593750,14.687500,15.500000,7843200,0.0,0.0,amd,AMD,technology,usa,2000
2,2000-01-03,36.457976,36.846240,34.788441,36.205605,53228400,0.0,0.0,microsoft,MSFT,technology,usa,2000
3,2000-01-03,23.135441,23.295548,22.495014,23.075401,2870400,0.0,0.0,target,TGT,retail,usa,2000
4,2000-01-03,9.653981,9.765803,9.355788,9.467610,3277800,0.0,0.0,southwest airlines,LUV,aviation,usa,2000

In [ ]:
df['Month']=df['Date'].dt.month

In [ ]:
df['Day']=df['Date'].dt.day

In [ ]:
df.head()

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits,Brand_Name,Ticker,Industry_Tag,Country,Year,Month,Day
0,2000-01-03,5.731675,5.793975,5.427959,5.482471,5825700,0.0,0.0,american eagle outfitters,AEO,apparel,usa,2000,1,3
1,2000-01-03,14.968750,15.593750,14.687500,15.500000,7843200,0.0,0.0,amd,AMD,technology,usa,2000,1,3
2,2000-01-03,36.457976,36.846240,34.788441,36.205605,53228400,0.0,0.0,microsoft,MSFT,technology,usa,2000,1,3
3,2000-01-03,23.135441,23.295548,22.495014,23.075401,2870400,0.0,0.0,target,TGT,retail,usa,2000,1,3
4,2000-01-03,9.653981,9.765803,9.355788,9.467610,3277800,0.0,0.0,southwest airlines,LUV,aviation,usa,2000,1,3

In [ ]:
df.tail()

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits,Brand_Name,Ticker,Industry_Tag,Country,Year,Month,Day
305209,2025-03-20,17.959999,17.959999,17.700001,17.770000,545600,0.0,0.0,nintendo,NTDOY,gaming,japan,2025,3,20
305210,2025-03-20,106.820000,108.970001,105.379997,105.480003,1481100,0.0,0.0,crocs,CROX,footwear,usa,2025,3,20
305211,2025-03-20,48.500000,49.349998,48.490002,49.000000,10706600,0.0,0.0,chipotle,CMG,food,usa,2025,3,20
305212,2025-03-20,104.400002,106.669998,103.919998,104.199997,5853100,0.0,0.0,target,TGT,retail,usa,2025,3,20
305213,2025-03-20,386.899994,397.820007,385.799988,389.609985,4003800,0.0,0.0,adobe,ADBE,technology,usa,2025,3,20

In [ ]:
df['Daily Price']=df.groupby('Ticker')['Close'].pct_change()

In [ ]:
df.head(35)

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits,Brand_Name,Ticker,Industry_Tag,Country,Year,Month,Day,Daily Price
0,2000-01-03,5.731675,5.793975,5.427959,5.482471,5825700,0.0,0.0,american eagle outfitters,AEO,apparel,usa,2000,1,3,NaN
1,2000-01-03,14.968750,15.593750,14.687500,15.500000,7843200,0.0,0.0,amd,AMD,technology,usa,2000,1,3,NaN
2,2000-01-03,36.457976,36.846240,34.788441,36.205605,53228400,0.0,0.0,microsoft,MSFT,technology,usa,2000,1,3,NaN
3,2000-01-03,23.135441,23.295548,22.495014,23.075401,2870400,0.0,0.0,target,TGT,retail,usa,2000,1,3,NaN
4,2000-01-03,9.653981,9.765803,9.355788,9.467610,3277800,0.0,0.0,southwest airlines,LUV,aviation,usa,2000,1,3,NaN
5,2000-01-03,25.340536,25.510607,24.915359,25.085430,4642400,0.0,0.0,johnson & johnson,JNJ,healthcare,usa,2000,1,3,NaN
6,2000-01-03,72.313085,72.405794,71.756831,72.034958,21200,0.0,0.0,toyota,TM,automotive,japan,2000,1,3,NaN
7,2000-01-03,4.785835,4.810098,4.634192,4.670587,8014400,0.0,0.0,nike,NKE,apparel,usa,2000,1,3,NaN
8,2000-01-03,15.207880,15.207880,14.486817,14.781797,10997000,0.0,0.0,the coca-cola company,KO,food & beverage,usa,2000,1,3,NaN
9,2000-01-03,19.260617,19.260617,18.658722,18.733959,2434800,0.0,0.0,colgate palmolive,CL,consumer goods,usa,2000,1,3,NaN
10,2000-01-03,2.360523,2.440855,2.298729,2.437765,24232000,0.0,0.0,starbucks,SBUX,food & beverage,usa,2000,1,3,NaN
11,2000-01-03,24.863424,25.071313,23.990294,24.239759,12019200,0.0,0.0,jpmorgan chase & co,JPM,finance,usa,2000,1,3,NaN
12,2000-01-03,2.647906,2.659888,2.611962,2.632930,76000,0.0,0.0,logitech,LOGI,technology,switzerland,2000,1,3,NaN
13,2000-01-03,22.631671,23.163612,22.244805,23.115253,8402230,0.0,0.0,the walt disney company,DIS,entertainment,usa,2000,1,3,NaN
14,2000-01-03,19.481210,19.515179,18.903737,19.158504,3320000,0.0,0.0,philips,PHG,technology,netherlands,2000,1,3,NaN
15,2000-01-03,28.774989,28.808351,28.207830,28.608177,4275000,0.0,0.0,procter & gamble,PG,consumer goods,usa,2000,1,3,NaN
16,2000-01-03,7.289986,7.342182,7.098602,7.168196,882200,0.0,0.0,nordstrom,JWN,retail,usa,2000,1,3,NaN
17,2000-01-03,38.147537,38.255972,35.935457,37.496925,53076000,0.0,0.0,cisco,CSCO,technology,usa,2000,1,3,NaN
18,2000-01-03,25.215814,25.330655,24.690826,24.772856,2173400,0.0,0.0,3m,MMM,manufacturing,usa,2000,1,3,NaN
19,2000-01-03,31.512873,31.512873,30.431443,30.799129,6057400,0.0,0.0,costco,COST,retail,usa,2000,1,3,NaN
20,2000-01-03,3.990652,4.061914,3.848129,3.990652,134500,0.0,0.0,nintendo,NTDOY,gaming,japan,2000,1,3,NaN
21,2000-01-03,13.822670,13.822670,13.675379,13.720699,48000,0.0,0.0,honda,HMC,automotive,japan,2000,1,3,NaN
22,2000-01-03,3.992771,4.204777,3.922103,3.957437,240000,0.0,0.0,foot locker,FL,footwear,usa,2000,1,3,NaN
23,2000-01-03,0.794800,0.852586,0.770643,0.848323,535796800,0.0,0.0,apple,AAPL,technology,usa,2000,1,3,NaN
24,2000-01-03,0.903091,0.910259,0.843363,0.894729,30091200,0.0,0.0,nvidia,NVDA,technology,usa,2000,1,3,NaN
25,2000-01-03,42.196946,42.542823,39.237780,40.083256,12030800,0.0,0.0,the home depot,HD,retail,usa,2000,1,3,NaN
26,2000-01-03,13.765435,13.911876,13.490859,13.582384,906400,0.0,0.0,hershey company,HSY,food & beverage,usa,2000,1,3,NaN
27,2000-01-03,35.788786,36.844503,34.627498,36.263859,1734000,0.0,0.0,fedex,FDX,logistics,usa,2000,1,3,NaN
28,2000-01-03,34.729481,34.729481,32.934947,33.198849,6471267,0.0,0.0,american express,AXP,finance,usa,2000,1,3,NaN
29,2000-01-03,22.361069,22.431057,21.801168,22.186100,4520600,0.0,0.0,mcdonald's,MCD,food,usa,2000,1,3,NaN
30,2000-01-03,11.826695,11.850113,11.405149,11.428568,2506717,0.0,0.0,marriott,MAR,hospitality,usa,2000,1,3,NaN
31,2000-01-03,4.075000,4.478125,3.952344,4.468750,322352000,0.0,0.0,amazon,AMZN,e-commerce,usa,2000,1,3,NaN
32,2000-01-03,16.693566,16.755624,15.948872,16.274675,7384400,0.0,0.0,adobe,ADBE,technology,usa,2000,1,3,NaN
33,2000-01-03,7.534477,7.534477,7.363591,7.472337,490860,0.0,0.0,unilever,UL,consumer goods,netherlands,2000,1,3,NaN
34,2000-01-04,7.441265,7.550010,7.348055,7.363590,123300,0.0,0.0,unilever,UL,consumer goods,netherlands,2000,1,4,-0.014553

In [ ]:
df.tail()

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits,Brand_Name,Ticker,Industry_Tag,Country,Year,Month,Day,Daily Price
305209,2025-03-20,17.959999,17.959999,17.700001,17.770000,545600,0.0,0.0,nintendo,NTDOY,gaming,japan,2025,3,20,-0.003365
305210,2025-03-20,106.820000,108.970001,105.379997,105.480003,1481100,0.0,0.0,crocs,CROX,footwear,usa,2025,3,20,-0.014021
305211,2025-03-20,48.500000,49.349998,48.490002,49.000000,10706600,0.0,0.0,chipotle,CMG,food,usa,2025,3,20,0.000204
305212,2025-03-20,104.400002,106.669998,103.919998,104.199997,5853100,0.0,0.0,target,TGT,retail,usa,2025,3,20,-0.007052
305213,2025-03-20,386.899994,397.820007,385.799988,389.609985,4003800,0.0,0.0,adobe,ADBE,technology,usa,2025,3,20,0.004434

In [ ]:
df_UL=df[df['Ticker']=='UL']

In [ ]:
df_UL.head(20)

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits,Brand_Name,Ticker,Industry_Tag,Country,Year,Month,Day,Daily Price
33,2000-01-03,7.534477,7.534477,7.363591,7.472337,490860,0.0,0.0,unilever,UL,consumer goods,netherlands,2000,1,3,NaN
34,2000-01-04,7.441265,7.550010,7.348055,7.363590,123300,0.0,0.0,unilever,UL,consumer goods,netherlands,2000,1,4,-0.014553
90,2000-01-05,7.565544,7.783034,7.565544,7.674290,277920,0.0,0.0,unilever,UL,consumer goods,netherlands,2000,1,5,0.042194
124,2000-01-06,7.829638,7.984988,7.736429,7.829638,235080,0.0,0.0,unilever,UL,consumer goods,netherlands,2000,1,6,0.020243
145,2000-01-07,8.016058,8.264617,8.016058,8.264617,207720,0.0,0.0,unilever,UL,consumer goods,netherlands,2000,1,7,0.055555
176,2000-01-10,7.984992,8.047132,7.798572,7.969457,190440,0.0,0.0,unilever,UL,consumer goods,netherlands,2000,1,10,-0.035714
228,2000-01-11,7.829639,8.016059,7.783033,7.891779,147420,0.0,0.0,unilever,UL,consumer goods,netherlands,2000,1,11,-0.009747
249,2000-01-12,7.845175,7.953921,7.829640,7.922850,86940,0.0,0.0,unilever,UL,consumer goods,netherlands,2000,1,12,0.003937
285,2000-01-13,7.938385,7.953920,7.829640,7.876245,81720,0.0,0.0,unilever,UL,consumer goods,netherlands,2000,1,13,-0.005882
321,2000-01-14,7.829640,8.016061,7.798570,7.907315,300780,0.0,0.0,unilever,UL,consumer goods,netherlands,2000,1,14,0.003945
355,2000-01-18,7.581082,7.596618,7.441267,7.550012,259380,0.0,0.0,unilever,UL,consumer goods,netherlands,2000,1,18,-0.045186
391,2000-01-19,7.208240,7.301450,7.146100,7.254845,593640,0.0,0.0,unilever,UL,consumer goods,netherlands,2000,1,19,-0.039095
417,2000-01-20,7.146100,7.177171,7.006285,7.115030,322740,0.0,0.0,unilever,UL,consumer goods,netherlands,2000,1,20,-0.019272
467,2000-01-21,6.959682,7.083961,6.897542,6.928611,418140,0.0,0.0,unilever,UL,consumer goods,netherlands,2000,1,21,-0.026201
484,2000-01-24,7.021819,7.021819,6.835399,6.866469,376740,0.0,0.0,unilever,UL,consumer goods,netherlands,2000,1,24,-0.008969
539,2000-01-25,6.680050,6.990749,6.680050,6.819865,404640,0.0,0.0,unilever,UL,consumer goods,netherlands,2000,1,25,-0.006787
547,2000-01-26,6.711119,6.773260,6.664514,6.773260,244620,0.0,0.0,unilever,UL,consumer goods,netherlands,2000,1,26,-0.006834
606,2000-01-27,6.524700,6.617910,6.369350,6.617910,916200,0.0,0.0,unilever,UL,consumer goods,netherlands,2000,1,27,-0.022936
636,2000-01-28,6.447027,6.462562,6.353817,6.384887,573300,0.0,0.0,unilever,UL,consumer goods,netherlands,2000,1,28,-0.035211
659,2000-01-31,6.276137,6.478092,6.213997,6.400417,640980,0.0,0.0,unilever,UL,consumer goods,netherlands,2000,1,31,0.002432

In [ ]:
df['Price Range']=df['High']-df['Low']

In [ ]:
df.head()

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits,Brand_Name,Ticker,Industry_Tag,Country,Year,Month,Day,Daily Price,Price Range
0,2000-01-03,5.731675,5.793975,5.427959,5.482471,5825700,0.0,0.0,american eagle outfitters,AEO,apparel,usa,2000,1,3,NaN,0.366017
1,2000-01-03,14.968750,15.593750,14.687500,15.500000,7843200,0.0,0.0,amd,AMD,technology,usa,2000,1,3,NaN,0.906250
2,2000-01-03,36.457976,36.846240,34.788441,36.205605,53228400,0.0,0.0,microsoft,MSFT,technology,usa,2000,1,3,NaN,2.057798
3,2000-01-03,23.135441,23.295548,22.495014,23.075401,2870400,0.0,0.0,target,TGT,retail,usa,2000,1,3,NaN,0.800534
4,2000-01-03,9.653981,9.765803,9.355788,9.467610,3277800,0.0,0.0,southwest airlines,LUV,aviation,usa,2000,1,3,NaN,0.410015

In [ ]:
df.columns

Index(['Date', 'Open', 'High', 'Low', 'Close', 'Volume', 'Dividends',
       'Stock Splits', 'Brand_Name', 'Ticker', 'Industry_Tag', 'Country',
       'Year', 'Month', 'Day', 'Daily Price', 'Price Range'],
      dtype='object')

#EXPLORATRY DATA ANALYSIS EDA

#TIME SERIES CHARTS

In [ ]:
import plotly.express as px
import plotly.graph_objects as go

In [ ]:
#FILTER DATA

df['Ticker']=='AAPL'
df[df['Ticker']=='AAPL']

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits,Brand_Name,Ticker,Industry_Tag,Country,Year,Month,Day,Daily Price,Price Range
23,2000-01-03,0.794800,0.852586,0.770643,0.848323,535796800,0.0,0.0,apple,AAPL,technology,usa,2000,1,3,NaN,0.081943
65,2000-01-04,0.820377,0.838376,0.766854,0.776801,512377600,0.0,0.0,apple,AAPL,technology,usa,2000,1,4,-0.084310,0.071522
100,2000-01-05,0.786273,0.837902,0.780590,0.788168,778321600,0.0,0.0,apple,AAPL,technology,usa,2000,1,5,0.014633,0.057312
130,2000-01-06,0.804273,0.810904,0.719961,0.719961,767972800,0.0,0.0,apple,AAPL,technology,usa,2000,1,6,-0.086538,0.090943
142,2000-01-07,0.731329,0.765433,0.723751,0.754065,460734400,0.0,0.0,apple,AAPL,technology,usa,2000,1,7,0.047369,0.041682
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
304913,2025-03-14,211.250000,213.949997,209.580002,213.490005,60060200,0.0,0.0,apple,AAPL,technology,usa,2025,3,14,0.000000,4.369995
304991,2025-03-17,213.309998,215.220001,209.970001,214.000000,48042800,0.0,0.0,apple,AAPL,technology,usa,2025,3,17,0.002389,5.250000
305081,2025-03-18,214.160004,215.149994,211.490005,212.690002,42391800,0.0,0.0,apple,AAPL,technology,usa,2025,3,18,-0.006121,3.659988
305114,2025-03-19,214.220001,218.759995,213.750000,215.240005,54336700,0.0,0.0,apple,AAPL,technology,usa,2025,3,19,0.011989,5.009995
305202,2025-03-20,213.990005,217.490005,212.220001,214.100006,48799300,0.0,0.0,apple,AAPL,technology,usa,2025,3,20,-0.005296,5.270004

In [ ]:
ticker='AAPL'
stock_data=df[df['Ticker']==ticker]
stock_data

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits,Brand_Name,Ticker,Industry_Tag,Country,Year,Month,Day,Daily Price,Price Range
23,2000-01-03,0.794800,0.852586,0.770643,0.848323,535796800,0.0,0.0,apple,AAPL,technology,usa,2000,1,3,NaN,0.081943
65,2000-01-04,0.820377,0.838376,0.766854,0.776801,512377600,0.0,0.0,apple,AAPL,technology,usa,2000,1,4,-0.084310,0.071522
100,2000-01-05,0.786273,0.837902,0.780590,0.788168,778321600,0.0,0.0,apple,AAPL,technology,usa,2000,1,5,0.014633,0.057312
130,2000-01-06,0.804273,0.810904,0.719961,0.719961,767972800,0.0,0.0,apple,AAPL,technology,usa,2000,1,6,-0.086538,0.090943
142,2000-01-07,0.731329,0.765433,0.723751,0.754065,460734400,0.0,0.0,apple,AAPL,technology,usa,2000,1,7,0.047369,0.041682
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
304913,2025-03-14,211.250000,213.949997,209.580002,213.490005,60060200,0.0,0.0,apple,AAPL,technology,usa,2025,3,14,0.000000,4.369995
304991,2025-03-17,213.309998,215.220001,209.970001,214.000000,48042800,0.0,0.0,apple,AAPL,technology,usa,2025,3,17,0.002389,5.250000
305081,2025-03-18,214.160004,215.149994,211.490005,212.690002,42391800,0.0,0.0,apple,AAPL,technology,usa,2025,3,18,-0.006121,3.659988
305114,2025-03-19,214.220001,218.759995,213.750000,215.240005,54336700,0.0,0.0,apple,AAPL,technology,usa,2025,3,19,0.011989,5.009995
305202,2025-03-20,213.990005,217.490005,212.220001,214.100006,48799300,0.0,0.0,apple,AAPL,technology,usa,2025,3,20,-0.005296,5.270004

In [ ]:
ticker='AAPL'
stock_date=df[df['Ticker']==ticker]
stock_date

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits,Brand_Name,Ticker,Industry_Tag,Country,Year,Month,Day,Daily Price,Price Range
23,2000-01-03,0.794800,0.852586,0.770643,0.848323,535796800,0.0,0.0,apple,AAPL,technology,usa,2000,1,3,NaN,0.081943
65,2000-01-04,0.820377,0.838376,0.766854,0.776801,512377600,0.0,0.0,apple,AAPL,technology,usa,2000,1,4,-0.084310,0.071522
100,2000-01-05,0.786273,0.837902,0.780590,0.788168,778321600,0.0,0.0,apple,AAPL,technology,usa,2000,1,5,0.014633,0.057312
130,2000-01-06,0.804273,0.810904,0.719961,0.719961,767972800,0.0,0.0,apple,AAPL,technology,usa,2000,1,6,-0.086538,0.090943
142,2000-01-07,0.731329,0.765433,0.723751,0.754065,460734400,0.0,0.0,apple,AAPL,technology,usa,2000,1,7,0.047369,0.041682
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
304913,2025-03-14,211.250000,213.949997,209.580002,213.490005,60060200,0.0,0.0,apple,AAPL,technology,usa,2025,3,14,0.000000,4.369995
304991,2025-03-17,213.309998,215.220001,209.970001,214.000000,48042800,0.0,0.0,apple,AAPL,technology,usa,2025,3,17,0.002389,5.250000
305081,2025-03-18,214.160004,215.149994,211.490005,212.690002,42391800,0.0,0.0,apple,AAPL,technology,usa,2025,3,18,-0.006121,3.659988
305114,2025-03-19,214.220001,218.759995,213.750000,215.240005,54336700,0.0,0.0,apple,AAPL,technology,usa,2025,3,19,0.011989,5.009995
305202,2025-03-20,213.990005,217.490005,212.220001,214.100006,48799300,0.0,0.0,apple,AAPL,technology,usa,2025,3,20,-0.005296,5.270004

In [ ]:
fig=go.Figure([go.Scatter(x=stock_date['Date'],y=stock_date['Close'],mode='lines',name=ticker)])

fig.update_layout(title=f'Stock Price History:{ticker}',
                  xaxis_title='Date',
                  yaxis_title='Closing Price',
                  template='plotly_white',
                  height=450,
                  width=800,
                  yaxis=dict(tickformat='$.2f'),
                  legend_title='Ticker')
fig.show()

#MULTIPLE STOCK COMPARISION

In [ ]:
selected_ticker=['AMZN','GOOGL','MSFT']
filtered_df=df[df['Ticker'].isin(selected_ticker)]
filtered_df

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits,Brand_Name,Ticker,Industry_Tag,Country,Year,Month,Day,Daily Price,Price Range
2,2000-01-03,36.457976,36.846240,34.788441,36.205605,53228400,0.0,0.0,microsoft,MSFT,technology,usa,2000,1,3,NaN,2.057798
31,2000-01-03,4.075000,4.478125,3.952344,4.468750,322352000,0.0,0.0,amazon,AMZN,e-commerce,usa,2000,1,3,NaN,0.525781
37,2000-01-04,35.273749,36.380301,34.866072,34.982552,54119000,0.0,0.0,microsoft,MSFT,technology,usa,2000,1,4,-0.033781,1.514228
67,2000-01-04,4.268750,4.575000,4.087500,4.096875,349748000,0.0,0.0,amazon,AMZN,e-commerce,usa,2000,1,4,-0.083217,0.487500
82,2000-01-05,3.525000,3.756250,3.400000,3.487500,769148000,0.0,0.0,amazon,AMZN,e-commerce,usa,2000,1,5,-0.148741,0.356250
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
305115,2025-03-19,193.380005,195.970001,191.960007,195.539993,39334200,0.0,0.0,amazon,AMZN,e-commerce,usa,2025,3,19,0.014106,4.009995
305119,2025-03-19,385.529999,389.679993,384.000000,387.820007,19165300,0.0,0.0,microsoft,MSFT,technology,usa,2025,3,19,0.011212,5.679993
305199,2025-03-20,385.739990,391.790008,383.279999,386.839996,18454000,0.0,0.0,microsoft,MSFT,technology,usa,2025,3,20,-0.002527,8.510010
305201,2025-03-20,193.070007,199.320007,192.300003,194.949997,38861300,0.0,0.0,amazon,AMZN,e-commerce,usa,2025,3,20,-0.003017,7.020004
305203,2025-03-20,161.570007,164.889999,160.960007,162.800003,28104400,0.0,0.0,google,GOOGL,technology,usa,2025,3,20,-0.006651,3.929993

In [ ]:
filtered_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 17999 entries, 2 to 305203
Data columns (total 17 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Date          17999 non-null  datetime64[ns]
 1   Open          17999 non-null  float64
 2   High          17999 non-null  float64
 3   Low           17999 non-null  float64
 4   Close         17999 non-null  float64
 5   Volume        17999 non-null  int64
 6   Dividends     17999 non-null  float64
 7   Stock Splits  17999 non-null  float64
 8   Brand_Name    17999 non-null  category
 9   Ticker        17999 non-null  category
 10  Industry_Tag  17999 non-null  category
 11  Country       17999 non-null  category
 12  Year          17999 non-null  int32
 13  Month         17999 non-null  int32
 14  Day           17999 non-null  int32
 15  Daily Price   17996 non-null  float64
 16  Price Range   17999 non-null  float64
dtypes: category(4), datetime64[ns](1), float64(8), int32(3), int64(1)
memory usage: 1.8 MB

In [ ]:
filtered_df.shape

(17999, 17)

In [ ]:
fig = go.Figure()
for ticker in selected_ticker:
    stock_data = filtered_df[filtered_df['Ticker'] == ticker]
    fig.add_trace(go.Scatter(x=stock_data['Date'],
                             y=stock_data['Close'],
                             mode='lines',
                             name=ticker))

# Update layout
fig.update_layout(title='Stock Price History: Closing Prices Over Time',
                  xaxis_title='Date',
                  yaxis_title='Closing Price',
                  template='plotly_white',
                  height=500,
                  width=850,
                  yaxis=dict(tickformat='$.2f'),
                  legend_title='Ticker')
fig.show()

#MOVING AVERAGE CHART
Line charts including 50-day and 200-day moving averages to identify short- and long-term trends.

In [ ]:
df[(df['Ticker'] == 'AAPL') & (df['Year']>=2020) & (df['Year'] <= 2025)]

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits,Brand_Name,Ticker,Industry_Tag,Country,Year,Month,Day,Daily Price,Price Range
223526,2020-01-02,72.246685,73.310001,71.990615,73.249031,135480400,0.0,0.0,apple,AAPL,technology,usa,2020,1,2,0.022816,1.319386
223618,2020-01-03,72.468602,73.305105,72.310083,72.536888,146322800,0.0,0.0,apple,AAPL,technology,usa,2020,1,3,-0.009722,0.995022
223678,2020-01-06,71.649176,73.153905,71.395540,73.114883,118387200,0.0,0.0,apple,AAPL,technology,usa,2020,1,6,0.007968,1.758365
223701,2020-01-07,73.124639,73.383150,72.549088,72.771019,108872000,0.0,0.0,apple,AAPL,technology,usa,2020,1,7,-0.004703,0.834062
223755,2020-01-08,72.471053,74.246491,72.471053,73.941643,132079200,0.0,0.0,apple,AAPL,technology,usa,2020,1,8,0.016086,1.775438
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
304913,2025-03-14,211.250000,213.949997,209.580002,213.490005,60060200,0.0,0.0,apple,AAPL,technology,usa,2025,3,14,0.000000,4.369995
304991,2025-03-17,213.309998,215.220001,209.970001,214.000000,48042800,0.0,0.0,apple,AAPL,technology,usa,2025,3,17,0.002389,5.250000
305081,2025-03-18,214.160004,215.149994,211.490005,212.690002,42391800,0.0,0.0,apple,AAPL,technology,usa,2025,3,18,-0.006121,3.659988
305114,2025-03-19,214.220001,218.759995,213.750000,215.240005,54336700,0.0,0.0,apple,AAPL,technology,usa,2025,3,19,0.011989,5.009995
305202,2025-03-20,213.990005,217.490005,212.220001,214.100006,48799300,0.0,0.0,apple,AAPL,technology,usa,2025,3,20,-0.005296,5.270004

In [ ]:
aapl_df = df[(df['Ticker'] == 'AAPL') & (df['Year'] >= 2020) & (df['Year'] <= 2025)].sort_values('Date')
aapl_df.head()

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits,Brand_Name,Ticker,Industry_Tag,Country,Year,Month,Day,Daily Price,Price Range
223526,2020-01-02,72.246685,73.310001,71.990615,73.249031,135480400,0.0,0.0,apple,AAPL,technology,usa,2020,1,2,0.022816,1.319386
223618,2020-01-03,72.468602,73.305105,72.310083,72.536888,146322800,0.0,0.0,apple,AAPL,technology,usa,2020,1,3,-0.009722,0.995022
223678,2020-01-06,71.649176,73.153905,71.395540,73.114883,118387200,0.0,0.0,apple,AAPL,technology,usa,2020,1,6,0.007968,1.758365
223701,2020-01-07,73.124639,73.383150,72.549088,72.771019,108872000,0.0,0.0,apple,AAPL,technology,usa,2020,1,7,-0.004703,0.834062
223755,2020-01-08,72.471053,74.246491,72.471053,73.941643,132079200,0.0,0.0,apple,AAPL,technology,usa,2020,1,8,0.016086,1.775438

In [ ]:
aapl_df['MA_50']=aapl_df['Close'].rolling(window=50).mean()
aapl_df['MA_200']=aapl_df['Close'].rolling(window=200).mean()
aapl_df['MA_50']

223526         NaN
223618         NaN
223678         NaN
223701         NaN
223755         NaN
            ...
304913    233.5072
304991    233.0298
305081    232.7184
305114    232.4236
305202    232.1060
Name: MA_50, Length: 1356, dtype: float64

In [ ]:
aapl_df['MA_200']

223526          NaN
223618          NaN
223678          NaN
223701          NaN
223755          NaN
            ...
304913    231.60140
304991    231.54985
305081    231.49350
305114    231.44465
305202    231.42245
Name: MA_200, Length: 1356, dtype: float64

In [ ]:

fig = go.Figure()
fig.add_trace(go.Scatter(x=aapl_df['Date'], y=aapl_df['Close'], mode='lines', name='Close'))
fig.add_trace(go.Scatter(x=aapl_df['Date'], y=aapl_df['MA_50'], mode='lines', name='50-day MA'))
fig.add_trace(go.Scatter(x=aapl_df['Date'], y=aapl_df['MA_200'], mode='lines', name='200-day MA'))

fig.update_layout(title='AAPL - Moving Average Chart',
                  xaxis_title='Date',
                  yaxis_title='Price',
                  template='plotly_white',
                  height=450,
                  width=850,
                  yaxis=dict(tickformat='$.2f'),
                  legend_title='Line')

fig.show()

#CARDLISTICK CHART
Charts displaying daily open, high, low, and close prices to analyze detailed price patterns.

In [ ]:
aapl_df = df[(df['Ticker'] == 'AAPL') & (df['Year'] >= 2020) & (df['Year'] <= 2025)].sort_values('Date')
aapl_df.set_index('Date',inplace=True)
aapl_df.head()

,Open,High,Low,Close,Volume,Dividends,Stock Splits,Brand_Name,Ticker,Industry_Tag,Country,Year,Month,Day,Daily Price,Price Range
Date,,,,,,,,,,,,,,,,
2020-01-02,72.246685,73.310001,71.990615,73.249031,135480400,0.0,0.0,apple,AAPL,technology,usa,2020,1,2,0.022816,1.319386
2020-01-03,72.468602,73.305105,72.310083,72.536888,146322800,0.0,0.0,apple,AAPL,technology,usa,2020,1,3,-0.009722,0.995022
2020-01-06,71.649176,73.153905,71.395540,73.114883,118387200,0.0,0.0,apple,AAPL,technology,usa,2020,1,6,0.007968,1.758365
2020-01-07,73.124639,73.383150,72.549088,72.771019,108872000,0.0,0.0,apple,AAPL,technology,usa,2020,1,7,-0.004703,0.834062
2020-01-08,72.471053,74.246491,72.471053,73.941643,132079200,0.0,0.0,apple,AAPL,technology,usa,2020,1,8,0.016086,1.775438

In [ ]:
aapl_df.shape

(1356, 16)

In [ ]:
monthly_aapl = aapl_df.resample('M').agg({'Open': 'first',
                                          'High': 'max',
                                          'Low': 'min',
                                          'Close': 'last',
                                          'Volume': 'sum'}).reset_index()

monthly_aapl.head()

        Date       Open       High        Low      Close      Volume
0 2020-01-31  72.246685  79.955695  71.395540  75.482971  2934370400
1 2020-02-29  74.212334  79.991451  62.671625  66.824959  3019279200
2 2020-03-31  69.005524  74.315131  51.974148  62.163139  6280072400
3 2020-04-30  60.258817  72.000120  57.912024  71.821663  3265299200
4 2020-05-31  69.976010  79.477515  69.878228  77.933281  2805936000

In [ ]:
monthly_aapl.shape

(63, 6)

In [ ]:
fig = go.Figure(data=[go.Candlestick(x=monthly_aapl['Date'],
                                     open=monthly_aapl['Open'],
                                     high=monthly_aapl['High'],
                                     low=monthly_aapl['Low'],
                                     close=monthly_aapl['Close'],
                                     name='AAPL Monthly')])

fig.update_layout(title='AAPL - Monthly Candlestick Chart (2020-2025)',
                  xaxis_title='Date',
                  yaxis_title='Price',
                  xaxis_rangeslider_visible=True,
                  template='plotly_white',
                  height=500,
                  width=800,
                  yaxis=dict(tickformat='$.2f'),
                  xaxis=dict(tickformat='%b %Y'))
fig.show()

#RETURN ANALYSIS CHARTS
Daily Returns Distribution

In [ ]:
ticker='AAPL'
aapl_df=df[df['Ticker']==ticker]
aapl_df

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits,Brand_Name,Ticker,Industry_Tag,Country,Year,Month,Day,Daily Price,Price Range
23,2000-01-03,0.794800,0.852586,0.770643,0.848323,535796800,0.0,0.0,apple,AAPL,technology,usa,2000,1,3,NaN,0.081943
65,2000-01-04,0.820377,0.838376,0.766854,0.776801,512377600,0.0,0.0,apple,AAPL,technology,usa,2000,1,4,-0.084310,0.071522
100,2000-01-05,0.786273,0.837902,0.780590,0.788168,778321600,0.0,0.0,apple,AAPL,technology,usa,2000,1,5,0.014633,0.057312
130,2000-01-06,0.804273,0.810904,0.719961,0.719961,767972800,0.0,0.0,apple,AAPL,technology,usa,2000,1,6,-0.086538,0.090943
142,2000-01-07,0.731329,0.765433,0.723751,0.754065,460734400,0.0,0.0,apple,AAPL,technology,usa,2000,1,7,0.047369,0.041682
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
304913,2025-03-14,211.250000,213.949997,209.580002,213.490005,60060200,0.0,0.0,apple,AAPL,technology,usa,2025,3,14,0.000000,4.369995
304991,2025-03-17,213.309998,215.220001,209.970001,214.000000,48042800,0.0,0.0,apple,AAPL,technology,usa,2025,3,17,0.002389,5.250000
305081,2025-03-18,214.160004,215.149994,211.490005,212.690002,42391800,0.0,0.0,apple,AAPL,technology,usa,2025,3,18,-0.006121,3.659988
305114,2025-03-19,214.220001,218.759995,213.750000,215.240005,54336700,0.0,0.0,apple,AAPL,technology,usa,2025,3,19,0.011989,5.009995
305202,2025-03-20,213.990005,217.490005,212.220001,214.100006,48799300,0.0,0.0,apple,AAPL,technology,usa,2025,3,20,-0.005296,5.270004

In [ ]:
aapl_df.shape

(6387, 17)

#HISTOGRAM

In [ ]:
fig=px.histogram(aapl_df,
                 x='Daily Price',
                 nbins=100,
                 title='AAPL - Daily Returns Distribution',
                 labels={'Daily_Returns':'Daily Return (%)',},
                 marginal='box',
                 height=600,
                 width=800,
                 template='plotly_white')
fig.show()

#CUMMULATIVE RETURNS

In [ ]:
ticker='AAPL'
aapl_df=df[df['Ticker']==ticker]
aapl_df

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits,Brand_Name,Ticker,Industry_Tag,Country,Year,Month,Day,Daily Price,Price Range
23,2000-01-03,0.794800,0.852586,0.770643,0.848323,535796800,0.0,0.0,apple,AAPL,technology,usa,2000,1,3,NaN,0.081943
65,2000-01-04,0.820377,0.838376,0.766854,0.776801,512377600,0.0,0.0,apple,AAPL,technology,usa,2000,1,4,-0.084310,0.071522
100,2000-01-05,0.786273,0.837902,0.780590,0.788168,778321600,0.0,0.0,apple,AAPL,technology,usa,2000,1,5,0.014633,0.057312
130,2000-01-06,0.804273,0.810904,0.719961,0.719961,767972800,0.0,0.0,apple,AAPL,technology,usa,2000,1,6,-0.086538,0.090943
142,2000-01-07,0.731329,0.765433,0.723751,0.754065,460734400,0.0,0.0,apple,AAPL,technology,usa,2000,1,7,0.047369,0.041682
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
304913,2025-03-14,211.250000,213.949997,209.580002,213.490005,60060200,0.0,0.0,apple,AAPL,technology,usa,2025,3,14,0.000000,4.369995
304991,2025-03-17,213.309998,215.220001,209.970001,214.000000,48042800,0.0,0.0,apple,AAPL,technology,usa,2025,3,17,0.002389,5.250000
305081,2025-03-18,214.160004,215.149994,211.490005,212.690002,42391800,0.0,0.0,apple,AAPL,technology,usa,2025,3,18,-0.006121,3.659988
305114,2025-03-19,214.220001,218.759995,213.750000,215.240005,54336700,0.0,0.0,apple,AAPL,technology,usa,2025,3,19,0.011989,5.009995
305202,2025-03-20,213.990005,217.490005,212.220001,214.100006,48799300,0.0,0.0,apple,AAPL,technology,usa,2025,3,20,-0.005296,5.270004

In [ ]:
aapl_df['Cummulative_Return']=(1+aapl_df['Daily Price']).cumprod()-1
aapl_df

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits,Brand_Name,Ticker,Industry_Tag,Country,Year,Month,Day,Daily Price,Price Range,Cummulative_Return
23,2000-01-03,0.794800,0.852586,0.770643,0.848323,535796800,0.0,0.0,apple,AAPL,technology,usa,2000,1,3,NaN,0.081943,NaN
65,2000-01-04,0.820377,0.838376,0.766854,0.776801,512377600,0.0,0.0,apple,AAPL,technology,usa,2000,1,4,-0.084310,0.071522,-0.084310
100,2000-01-05,0.786273,0.837902,0.780590,0.788168,778321600,0.0,0.0,apple,AAPL,technology,usa,2000,1,5,0.014633,0.057312,-0.070911
130,2000-01-06,0.804273,0.810904,0.719961,0.719961,767972800,0.0,0.0,apple,AAPL,technology,usa,2000,1,6,-0.086538,0.090943,-0.151312
142,2000-01-07,0.731329,0.765433,0.723751,0.754065,460734400,0.0,0.0,apple,AAPL,technology,usa,2000,1,7,0.047369,0.041682,-0.111111
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
304913,2025-03-14,211.250000,213.949997,209.580002,213.490005,60060200,0.0,0.0,apple,AAPL,technology,usa,2025,3,14,0.000000,4.369995,250.661229
304991,2025-03-17,213.309998,215.220001,209.970001,214.000000,48042800,0.0,0.0,apple,AAPL,technology,usa,2025,3,17,0.002389,5.250000,251.262408
305081,2025-03-18,214.160004,215.149994,211.490005,212.690002,42391800,0.0,0.0,apple,AAPL,technology,usa,2025,3,18,-0.006121,3.659988,249.718188
305114,2025-03-19,214.220001,218.759995,213.750000,215.240005,54336700,0.0,0.0,apple,AAPL,technology,usa,2025,3,19,0.011989,5.009995,252.724122
305202,2025-03-20,213.990005,217.490005,212.220001,214.100006,48799300,0.0,0.0,apple,AAPL,technology,usa,2025,3,20,-0.005296,5.270004,251.380295

In [ ]:
aapl_df.dropna(subset=['Cummulative_Return'],inplace=True)
aapl_df['Cummulative_Return']

65         -0.084310
100        -0.070911
130        -0.151312
142        -0.111111
178        -0.126745
             ...
304913    250.661229
304991    251.262408
305081    249.718188
305114    252.724122
305202    251.380295
Name: Cummulative_Return, Length: 6386, dtype: float64

In [ ]:
[repr(col) for col in aapl_df.columns]

["'Date'",
 "'Open'",
 "'High'",
 "'Low'",
 "'Close'",
 "'Volume'",
 "'Dividends'",
 "'Stock Splits'",
 "'Brand_Name'",
 "'Ticker'",
 "'Industry_Tag'",
 "'Country'",
 "'Year'",
 "'Month'",
 "'Day'",
 "'Daily Price'",
 "'Price Range'",
 "'Cummulative_Return'"]

In [ ]:
aapl_df.columns=aapl_df.columns.str.strip()
aapl_df.columns

Index(['Date', 'Open', 'High', 'Low', 'Close', 'Volume', 'Dividends',
       'Stock Splits', 'Brand_Name', 'Ticker', 'Industry_Tag', 'Country',
       'Year', 'Month', 'Day', 'Daily Price', 'Price Range',
       'Cummulative_Return'],
      dtype='object')

In [ ]:
fig=px.line(aapl_df,
            x='Date',
            y='Cummulative_Return',
            title='AAPL Cummulative Return Over Time',
            labels={'Cummulative_Return'},
            height=700,
            width=800,
            template='plotly_white')
fig.show()

#HEAT MAP OF MONTHLY RETURN

In [ ]:
tech_tickers=['AAPL', 'MSFT', 'GOOGL', 'AMZN', 'META']
tech_df=df[df['Ticker'].isin(tech_tickers) & (df['Year']== 2023)]
tech_df.head()

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits,Brand_Name,Ticker,Industry_Tag,Country,Year,Month,Day,Daily Price,Price Range
268675,2023-01-03,241.432609,244.084512,235.791096,237.956329,25740000,0.0,0.0,microsoft,MSFT,technology,usa,2023,1,3,-0.001001,8.293417
268686,2023-01-03,129.726523,130.343885,123.642480,124.538658,112117500,0.0,0.0,apple,AAPL,technology,usa,2023,1,3,-0.037405,6.701404
268715,2023-01-03,85.459999,86.959999,84.209999,85.820000,76706000,0.0,0.0,amazon,AMZN,e-commerce,usa,2023,1,3,0.021667,2.750000
268717,2023-01-03,89.589996,91.050003,88.519997,89.120003,28131200,0.0,0.0,google,GOOGL,technology,usa,2023,1,3,0.010087,2.530006
268750,2023-01-04,230.705789,231.291787,224.428629,227.547348,50623400,0.0,0.0,microsoft,MSFT,technology,usa,2023,1,4,-0.043743,6.863158

In [ ]:
# Calculate monthly returns for each stock
result_data = []

for ticker in tech_tickers:
    ticker_data = tech_df[tech_df['Ticker'] == ticker].copy()

    # Group by month
    monthly_groups = ticker_data.groupby(tech_df['Date'].dt.month)

    for month_num, group in monthly_groups:
        month_name = group['Date'].iloc[0].strftime('%b')

        # Get first and last trading day of month
        start_price = group.iloc[0]['Open']
        end_price = group.iloc[-1]['Close']

        # Calculate return
        monthly_return = ((end_price - start_price) / start_price) * 100

        result_data.append({'Ticker': ticker,
                            'Month': month_name,
                            'Month_num': month_num,  # Store month number for sorting
                            'Return': monthly_return})

# Convert to DataFrame
monthly_df = pd.DataFrame(result_data)
monthly_df.head()

  Ticker Month  Month_num     Return
0   AAPL   Jan          1  10.753760
1   AAPL   Feb          2   2.545717
2   AAPL   Mar          3  12.306736
3   AAPL   Apr          4   3.293356
4   AAPL   May          5   4.853006

In [ ]:
pivot_df=monthly_df.pivot(index='Month_num',columns='Ticker',values='Return')
pivot_df.sort_index(inplace=True)
pivot_df

Ticker          AAPL       AMZN      GOOGL       MSFT
Month_num
1          10.753760  20.676338  10.324813   1.945862
2           2.545717  -8.095187  -8.763045   0.824482
3          12.306736  10.035153  15.281173  14.970476
4           3.293356   3.079173   4.834453   7.238598
5           4.853006  14.892811  15.003750   7.211738
6           9.155881   8.012261  -2.540305   4.482563
7           1.377847   2.186199  11.304934  -0.964061
8          -4.135911   3.339567   4.121425  -2.009622
9          -9.880817  -8.848418  -4.910530  -5.236034
10         -0.262814   4.564737  -5.434041   6.902114
11         11.228214   9.054934   6.818728  11.739327
12          1.155883   4.068495   5.938109  -0.191106

In [ ]:
month_labels = [pd.Timestamp(2023,month,1).strftime('%b') for month in pivot_df.index]
fig=go.Figure(data=go.Heatmap(z=pivot_df.values,
                              x=pivot_df.columns,
                              y=month_labels,
                              colorscale=[[0,'maroon'],[0.5,'white'],[1,'green']],
                              zmid=0,
                              colorbar=dict(
                                  title='Monthly Return (%)',
                                  titleside='right'),
                              text=np.round(pivot_df.values,2),
                              texttemplate='%{text:.2f}%',
                              textfont={'size':12}))
fig.update_layout(title='Monthly Returns of 5  Tech stocks (2023)',
                  xaxis_title='Stock Ticker',
                  yaxis_title='Month',
                  height=600,
                  width=1200,
                  xaxis={'side':'top'})
fig.show()

#Returns Boxplots

In [ ]:
aapl_df=df[(df['Ticker']=='AAPL') & (df['Year']>=2020) & (df['Year']<=2025)].sort_values('Date')
fig=px.box(aapl_df.reset_index(),
           x='Year',
           y="Daily Price",
           title='AAPL Daily Return Distribution by Year',
           labels={'Daily Price':'Daily Return (%)'},
           height=450,
           width=800,
           template='plotly_white')
fig.show()

#VOLUME ANSLYSIS

In [ ]:
ticker='AAPL'
aapl_df=df[(df['Ticker']==ticker) & (df['Year']>=2020) & (df['Year']<=2025)].sort_values('Date')
aapl_df

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits,Brand_Name,Ticker,Industry_Tag,Country,Year,Month,Day,Daily Price,Price Range
223526,2020-01-02,72.246685,73.310001,71.990615,73.249031,135480400,0.0,0.0,apple,AAPL,technology,usa,2020,1,2,0.022816,1.319386
223618,2020-01-03,72.468602,73.305105,72.310083,72.536888,146322800,0.0,0.0,apple,AAPL,technology,usa,2020,1,3,-0.009722,0.995022
223678,2020-01-06,71.649176,73.153905,71.395540,73.114883,118387200,0.0,0.0,apple,AAPL,technology,usa,2020,1,6,0.007968,1.758365
223701,2020-01-07,73.124639,73.383150,72.549088,72.771019,108872000,0.0,0.0,apple,AAPL,technology,usa,2020,1,7,-0.004703,0.834062
223755,2020-01-08,72.471053,74.246491,72.471053,73.941643,132079200,0.0,0.0,apple,AAPL,technology,usa,2020,1,8,0.016086,1.775438
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
304913,2025-03-14,211.250000,213.949997,209.580002,213.490005,60060200,0.0,0.0,apple,AAPL,technology,usa,2025,3,14,0.000000,4.369995
304991,2025-03-17,213.309998,215.220001,209.970001,214.000000,48042800,0.0,0.0,apple,AAPL,technology,usa,2025,3,17,0.002389,5.250000
305081,2025-03-18,214.160004,215.149994,211.490005,212.690002,42391800,0.0,0.0,apple,AAPL,technology,usa,2025,3,18,-0.006121,3.659988
305114,2025-03-19,214.220001,218.759995,213.750000,215.240005,54336700,0.0,0.0,apple,AAPL,technology,usa,2025,3,19,0.011989,5.009995
305202,2025-03-20,213.990005,217.490005,212.220001,214.100006,48799300,0.0,0.0,apple,AAPL,technology,usa,2025,3,20,-0.005296,5.270004

In [ ]:
aapl_df['Volume_MA_100']=aapl_df['Volume'].rolling(window=100).mean()
aapl_df.head()

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits,Brand_Name,Ticker,Industry_Tag,Country,Year,Month,Day,Daily Price,Price Range,Volume_MA_100
223526,2020-01-02,72.246685,73.310001,71.990615,73.249031,135480400,0.0,0.0,apple,AAPL,technology,usa,2020,1,2,0.022816,1.319386,NaN
223618,2020-01-03,72.468602,73.305105,72.310083,72.536888,146322800,0.0,0.0,apple,AAPL,technology,usa,2020,1,3,-0.009722,0.995022,NaN
223678,2020-01-06,71.649176,73.153905,71.395540,73.114883,118387200,0.0,0.0,apple,AAPL,technology,usa,2020,1,6,0.007968,1.758365,NaN
223701,2020-01-07,73.124639,73.383150,72.549088,72.771019,108872000,0.0,0.0,apple,AAPL,technology,usa,2020,1,7,-0.004703,0.834062,NaN
223755,2020-01-08,72.471053,74.246491,72.471053,73.941643,132079200,0.0,0.0,apple,AAPL,technology,usa,2020,1,8,0.016086,1.775438,NaN

In [ ]:
fig=go.Figure()
fig.add_trace(go.Scatter(x=aapl_df['Date'],
                         y=aapl_df['Volume'],
                         name='Daily Volume',
                         mode='lines',
                         line=dict(color='blue')))

fig.add_trace(go.Scatter(x=aapl_df['Date'],
                         y=aapl_df['Volume_MA_100'],
                         name='100-day MA',
                         mode='lines',
                         line=dict(color='red',dash='dot')))

fig.update_layout(title='AAPL - Daily Volume and 100-day Moving Average',
                  xaxis_title='Date',
                  yaxis_title='Volume',
                  template='plotly_white',
                  height=450,
                  width=800,
                  legend=dict(orientation='h',y=1.1,x=0.7))
fig.show()

#VOLUME GROUPED BAR CHART

In [ ]:
tech_tickers=['AAPL','MSFT','GOOGL']
tech_names={'AAPL':'Apple','MSFT':'Microsoft','GOOGL':'Google'}
tech_df=df[(df['Ticker'].isin(tech_tickers)) &
         (df['Year']>=2020) & (df['Year']<=2025)].sort_values('Date')
tech_df[['Date','Ticker','Volume']].head()

             Date Ticker     Volume
223526 2020-01-02   AAPL  135480400
223541 2020-01-02  GOOGL   27278000
223551 2020-01-02   MSFT   22622100
223604 2020-01-03  GOOGL   23408000
223618 2020-01-03   AAPL  146322800

In [ ]:
yearly_volume=tech_df.groupby(['Year','Ticker'])['Volume'].sum().reset_index()
yearly_volume['Volume_Billions']=yearly_volume['Volume']/1_000_000_000

In [ ]:
fig=go.Figure()

for i,ticker in enumerate(tech_tickers):
    company_data=yearly_volume[yearly_volume['Ticker']==ticker]
    company_data

    fig.add_trace(go.Bar(x=company_data['Year'],
                         y=company_data['Volume_Billions'],
                         name=tech_names[ticker]))


fig.update_layout(title='Annual trading : Tech Coampanies (2020-2025)',
                   xaxis_title='Year',
                   yaxis_title='Volume(Billions)',
                   template='plotly_white',
                   barmode='group',
                   height=700,
                   width=800,
                   legend=dict(orientation='h',y=1.1,x=0.7)
                   )
fig.show()

#COMPRATIVE ANALYSIS CHART

CUMMULATIVE RETURN BY INDUSTRY

In [ ]:
df.head()

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits,Brand_Name,Ticker,Industry_Tag,Country,Year,Month,Day,Daily Price,Price Range
0,2000-01-03,5.731675,5.793975,5.427959,5.482471,5825700,0.0,0.0,american eagle outfitters,AEO,apparel,usa,2000,1,3,NaN,0.366017
1,2000-01-03,14.968750,15.593750,14.687500,15.500000,7843200,0.0,0.0,amd,AMD,technology,usa,2000,1,3,NaN,0.906250
2,2000-01-03,36.457976,36.846240,34.788441,36.205605,53228400,0.0,0.0,microsoft,MSFT,technology,usa,2000,1,3,NaN,2.057798
3,2000-01-03,23.135441,23.295548,22.495014,23.075401,2870400,0.0,0.0,target,TGT,retail,usa,2000,1,3,NaN,0.800534
4,2000-01-03,9.653981,9.765803,9.355788,9.467610,3277800,0.0,0.0,southwest airlines,LUV,aviation,usa,2000,1,3,NaN,0.410015

In [ ]:
df['Cummulative_Return']=(1+df['Daily Price']).groupby(df['Ticker']).cumprod()-1
df.head()

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits,Brand_Name,Ticker,Industry_Tag,Country,Year,Month,Day,Daily Price,Price Range,Cummulative_Return
0,2000-01-03,5.731675,5.793975,5.427959,5.482471,5825700,0.0,0.0,american eagle outfitters,AEO,apparel,usa,2000,1,3,NaN,0.366017,NaN
1,2000-01-03,14.968750,15.593750,14.687500,15.500000,7843200,0.0,0.0,amd,AMD,technology,usa,2000,1,3,NaN,0.906250,NaN
2,2000-01-03,36.457976,36.846240,34.788441,36.205605,53228400,0.0,0.0,microsoft,MSFT,technology,usa,2000,1,3,NaN,2.057798,NaN
3,2000-01-03,23.135441,23.295548,22.495014,23.075401,2870400,0.0,0.0,target,TGT,retail,usa,2000,1,3,NaN,0.800534,NaN
4,2000-01-03,9.653981,9.765803,9.355788,9.467610,3277800,0.0,0.0,southwest airlines,LUV,aviation,usa,2000,1,3,NaN,0.410015,NaN

In [ ]:
df.tail()

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits,Brand_Name,Ticker,Industry_Tag,Country,Year,Month,Day,Daily Price,Price Range,Cummulative_Return
305209,2025-03-20,17.959999,17.959999,17.700001,17.770000,545600,0.0,0.0,nintendo,NTDOY,gaming,japan,2025,3,20,-0.003365,0.259998,3.452906
305210,2025-03-20,106.820000,108.970001,105.379997,105.480003,1481100,0.0,0.0,crocs,CROX,footwear,usa,2025,3,20,-0.014021,3.590004,6.389142
305211,2025-03-20,48.500000,49.349998,48.490002,49.000000,10706600,0.0,0.0,chipotle,CMG,food,usa,2025,3,20,0.000204,0.859997,0.113636
305212,2025-03-20,104.400002,106.669998,103.919998,104.199997,5853100,0.0,0.0,target,TGT,retail,usa,2025,3,20,-0.007052,2.750000,3.515631
305213,2025-03-20,386.899994,397.820007,385.799988,389.609985,4003800,0.0,0.0,adobe,ADBE,technology,usa,2025,3,20,0.004434,12.020019,22.939647

In [ ]:
latest_data=df['Date'].max()
latest_data

Timestamp('2025-03-20 00:00:00')

In [ ]:
lastest_returns=df[df['Date']==latest_data]
lastest_returns

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits,Brand_Name,Ticker,Industry_Tag,Country,Year,Month,Day,Daily Price,Price Range,Cummulative_Return
305153,2025-03-20,151.649994,153.649994,151.089996,151.270004,2579000,0.0,0.0,3m,MMM,manufacturing,usa,2025,3,20,-0.012662,2.559998,5.106280
305154,2025-03-20,168.889999,169.210007,166.029999,167.550003,8785300,0.0,0.0,procter & gamble,PG,consumer goods,usa,2025,3,20,-0.006051,3.180008,4.856717
305155,2025-03-20,16.299999,16.639999,16.049999,16.049999,2689000,0.0,0.0,foot locker,FL,footwear,usa,2025,3,20,-0.029625,0.590000,3.055655
305156,2025-03-20,25.980000,26.190001,25.790001,25.879999,760100,0.0,0.0,philips,PHG,technology,netherlands,2025,3,20,-0.033607,0.400000,0.350836
305157,2025-03-20,24.250000,24.330000,24.250000,24.309999,1399500,0.0,0.0,nordstrom,JWN,retail,usa,2025,3,20,0.000823,0.080000,2.391369
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
305209,2025-03-20,17.959999,17.959999,17.700001,17.770000,545600,0.0,0.0,nintendo,NTDOY,gaming,japan,2025,3,20,-0.003365,0.259998,3.452906
305210,2025-03-20,106.820000,108.970001,105.379997,105.480003,1481100,0.0,0.0,crocs,CROX,footwear,usa,2025,3,20,-0.014021,3.590004,6.389142
305211,2025-03-20,48.500000,49.349998,48.490002,49.000000,10706600,0.0,0.0,chipotle,CMG,food,usa,2025,3,20,0.000204,0.859997,0.113636
305212,2025-03-20,104.400002,106.669998,103.919998,104.199997,5853100,0.0,0.0,target,TGT,retail,usa,2025,3,20,-0.007052,2.750000,3.515631
305213,2025-03-20,386.899994,397.820007,385.799988,389.609985,4003800,0.0,0.0,adobe,ADBE,technology,usa,2025,3,20,0.004434,12.020019,22.939647

In [ ]:
latest_date=df['Date'].max()
latest_returns=df[df['Date']==latest_date]

industry_performance=latest_returns.groupby('Industry_Tag')['Cummulative_Return'].mean().sort_values(ascending=False).reset_index()

top5_industries=industry_performance.head(5)

fig=px.bar(
    top5_industries,
    x='Industry_Tag',
    y='Cummulative_Return',
    title='Top 5 Industries by Average Cummulative Return',
    height=450,
    width=800,
    labels={'Cummulative_Return':'Avg Cummulative Return (%)'}
)

fig.update_layout(xaxis_title='Industry', yaxis_title='Cummulative Return (%)')
fig.update_traces(textposition='outside')

fig.show()

#VOLATILITY BY INDUSTRY

In [ ]:
industry_volatility=df.groupby('Industry_Tag')['Daily Price'].std().sort_values(ascending=False).reset_index()
industry_volatility

          Industry_Tag  Daily Price
0       cryptocurrency     0.054660
1              fitness     0.053093
2         social media     0.039036
3   financial services     0.036033
4             footwear     0.034343
5           e-commerce     0.033112
6         luxury goods     0.030244
7                music     0.029456
8               gaming     0.028599
9           technology     0.028230
10       entertainment     0.027683
11            aviation     0.026852
12             apparel     0.025482
13          automotive     0.022856
14              retail     0.022127
15             finance     0.021495
16         hospitality     0.021458
17                food     0.021273
18           logistics     0.019810
19     food & beverage     0.016468
20       manufacturing     0.015608
21      consumer goods     0.013726
22          healthcare     0.012006

In [ ]:
industry_volatility=df.groupby('Industry_Tag')['Daily Price'].std().sort_values(ascending=False).reset_index()
industry_volatility.rename(columns={'Daily Price':'Volatility'}, inplace=True)

top5_volatile=industry_volatility.head(5)

fig=px.bar(
    top5_volatile,
    x='Industry_Tag',
    y='Volatility',
    title='Top 5 Most Volatile Industries',
    height=450,
    width=800,
    labels={'Industry_Tag':'Industry','Volatility':'Volatility (Std Dev)'},
    template='plotly_white'
)

fig.update_layout(xaxis_tickangle=-30)
fig.show()

In [ ]:
industry_volatility.tail(5)

       Industry_Tag  Volatility
18        logistics    0.019810
19  food & beverage    0.016468
20    manufacturing    0.015608
21   consumer goods    0.013726
22       healthcare    0.012006

In [ ]:
top5_stable=industry_volatility.tail(5)

fig=px.bar(
    top5_stable,
    x='Industry_Tag',
    y='Volatility',
    title='Top 5 Most Stable Industries',
    height=450,
    width=800,
    labels={'Industry_Tag':'Industry','Volatility':'Volatility (Std Dev)'},
    template='plotly_white'
)
fig.show()

In [ ]:
aapl_df=df[df['Ticker']=='AAPL'].sort_values('Date')
aapl_df.head()

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits,Brand_Name,Ticker,Industry_Tag,Country,Year,Month,Day,Daily Price,Price Range,Cummulative_Return
23,2000-01-03,0.794800,0.852586,0.770643,0.848323,535796800,0.0,0.0,apple,AAPL,technology,usa,2000,1,3,NaN,0.081943,NaN
65,2000-01-04,0.820377,0.838376,0.766854,0.776801,512377600,0.0,0.0,apple,AAPL,technology,usa,2000,1,4,-0.084310,0.071522,-0.084310
100,2000-01-05,0.786273,0.837902,0.780590,0.788168,778321600,0.0,0.0,apple,AAPL,technology,usa,2000,1,5,0.014633,0.057312,-0.070911
130,2000-01-06,0.804273,0.810904,0.719961,0.719961,767972800,0.0,0.0,apple,AAPL,technology,usa,2000,1,6,-0.086538,0.090943,-0.151312
142,2000-01-07,0.731329,0.765433,0.723751,0.754065,460734400,0.0,0.0,apple,AAPL,technology,usa,2000,1,7,0.047369,0.041682,-0.111111

In [ ]:
monthly_avg_returns=aapl_df.groupby(['Year','Month'])['Daily Price'].mean().reset_index()
monthly_avg_returns

     Year  Month  Daily Price
0    2000      1    -0.002534
1    2000      2     0.005533
2    2000      3     0.008686
3    2000      4    -0.003572
4    2000      5    -0.016957
..    ...    ...          ...
298  2024     11     0.001932
299  2024     12     0.002030
300  2025      1    -0.002142
301  2025      2     0.001169
302  2025      3    -0.007431

[303 rows x 3 columns]

In [ ]:
fig=px.line(
    monthly_avg_returns.tail(60),
    x='Month',
    y='Daily Price',
    color='Year',
    title='AAPL Seasonal Patterns: Average Monthly Returns by Year',
    labels={'Daily Price': 'Average Daily Return','Month':'Month'},
    markers=True,
    template='plotly_white',
    height=400,
    width=800
)
fig.show()

In [ ]:
fig=px.line(
    monthly_avg_returns.head(60),
    x='Month',
    y='Daily Price',
    color='Year',
    title='AAPL Seasonal Patterns: Average Monthly Returns by Year',
    labels={'Daily Price': 'Average Daily Return','Month':'Month'},
    markers=True,
    template='plotly_white',
    height=400,
    width=800
)
fig.show()

#WEEKDAY AVERAGE RETURN

In [ ]:
aapl_df['Weekday']=aapl_df['Date'].dt.day_name()
aapl_df.head()

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits,Brand_Name,Ticker,Industry_Tag,Country,Year,Month,Day,Daily Price,Price Range,Cummulative_Return,Weekday
23,2000-01-03,0.794800,0.852586,0.770643,0.848323,535796800,0.0,0.0,apple,AAPL,technology,usa,2000,1,3,NaN,0.081943,NaN,Monday
65,2000-01-04,0.820377,0.838376,0.766854,0.776801,512377600,0.0,0.0,apple,AAPL,technology,usa,2000,1,4,-0.084310,0.071522,-0.084310,Tuesday
100,2000-01-05,0.786273,0.837902,0.780590,0.788168,778321600,0.0,0.0,apple,AAPL,technology,usa,2000,1,5,0.014633,0.057312,-0.070911,Wednesday
130,2000-01-06,0.804273,0.810904,0.719961,0.719961,767972800,0.0,0.0,apple,AAPL,technology,usa,2000,1,6,-0.086538,0.090943,-0.151312,Thursday
142,2000-01-07,0.731329,0.765433,0.723751,0.754065,460734400,0.0,0.0,apple,AAPL,technology,usa,2000,1,7,0.047369,0.041682,-0.111111,Friday

In [ ]:
aapl_df.tail()

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits,Brand_Name,Ticker,Industry_Tag,Country,Year,Month,Day,Daily Price,Price Range,Cummulative_Return,Weekday
304913,2025-03-14,211.250000,213.949997,209.580002,213.490005,60060200,0.0,0.0,apple,AAPL,technology,usa,2025,3,14,0.000000,4.369995,250.661229,Friday
304991,2025-03-17,213.309998,215.220001,209.970001,214.000000,48042800,0.0,0.0,apple,AAPL,technology,usa,2025,3,17,0.002389,5.250000,251.262408,Monday
305081,2025-03-18,214.160004,215.149994,211.490005,212.690002,42391800,0.0,0.0,apple,AAPL,technology,usa,2025,3,18,-0.006121,3.659988,249.718188,Tuesday
305114,2025-03-19,214.220001,218.759995,213.750000,215.240005,54336700,0.0,0.0,apple,AAPL,technology,usa,2025,3,19,0.011989,5.009995,252.724122,Wednesday
305202,2025-03-20,213.990005,217.490005,212.220001,214.100006,48799300,0.0,0.0,apple,AAPL,technology,usa,2025,3,20,-0.005296,5.270004,251.380295,Thursday

In [ ]:
weekday_avg_returns=aapl_df.groupby('Weekday')['Daily Price'].mean().reindex(['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday']).reset_index()
weekday_avg_returns

     Weekday  Daily Price
0     Monday     0.003041
1    Tuesday     0.001126
2  Wednesday     0.001366
3   Thursday     0.001322
4     Friday    -0.000805
5   Saturday          NaN
6     Sunday          NaN

In [ ]:
fig=px.bar(weekday_avg_returns,
           x='Weekday',
           y='Daily Price',
           title='AAPL Day of Week Effects: Average Daily Return by Weekday',
           height=400,
           width=800,
           labels={'Daily Price':'Average Return'},
           template='plotly_white'
           )
fig.show()